#########################
# project configuration #
#########################

# C++ project
language: cpp
dist: trusty
sudo: required

################
# build matrix #
################

matrix:
  include:

    # gcc 5.2
    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-5.2
        - CXXFLAGS=-std=c++14
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5.2', 'cmake']

    # gcc 6
    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-6
        - CXXFLAGS=-std=c++14
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'cmake']

    # gcc 7
    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-7
        - CXXFLAGS=-std=c++14
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'cmake']

    # gcc 8
    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-8
        - CXXFLAGS=-std=c++14
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'cmake']

################
# build script #
################

script:
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

  - uname -a
  - $CXX --version

  - mkdir -p build && cd build
  - cmake .. && cmake --build . --config Release
  - cd ..
