#########################
# project configuration #
#########################

# C++ project
language: cpp

################
# build matrix #
################

matrix:
  include:

    # gcc 6
    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-6
        - CXXFLAGS=-std=c++14
      addons:
        apt:
          packages: ['g++-6']

    # gcc 7
    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-7
        - CXXFLAGS=-std=c++14
      addons:
        apt:
          packages: ['g++-7']

    # gcc 8
    - os: linux
      compiler: gcc
      env:
        - COMPILER=g++-8
        - CXXFLAGS=-std=c++14
      addons:
        apt:
          packages: ['g++-8']

################
# build script #
################

script:
  - mkdir -p build && cd build
  - cmake .. && cmake --build . --config Release
  - cd ..
